Repository acronis/ui-component-library, pull requests merged in 2024-07, with the labels that each got.

#40 fix(docs): fix doc aliases
  packages/documentation/demos/accordion/AccordionColors.vue
  packages/documentation/demos/accordion/AccordionExpanded.vue
  packages/documentation/demos/accordion/AccordionModel.vue
  packages/documentation/demos/accordion/AccordionMultiple.vue
  packages/documentation/demos/accordion/AccordionPaddings.vue
  packages/documentation/demos/accordion/AccordionSizes.vue
  packages/documentation/demos/cell/CellBasic.vue
  packages/documentation/demos/chart/ChartBasic.vue
  packages/documentation/demos/chip/ChipBasic.vue
  packages/documentation/demos/chip/ChipMultiline.vue
  packages/documentation/demos/code/CodeBasic.vue
  packages/documentation/demos/container/ContainerBasic.vue
  packages/documentation/demos/fitted-actions/FittedActionsBasic.vue
  packages/documentation/demos/fitted-actions/FittedActionsMaximum.vue
  packages/documentation/demos/fitted-actions/FittedActionsMinimum.vue
  packages/documentation/demos/fitted-actions/FittedActionsReversed.vue
  packages/documentation/demos/fitted-actions/FittedActionsSingle.vue
  packages/documentation/demos/fitted-actions/FittedActionsWithoutDropdown.vue
  packages/documentation/demos/flex/FlexBasic.vue
  packages/documentation/demos/footer/FooterBasic.vue
  packages/documentation/demos/header/HeaderBasic.vue
  packages/documentation/demos/icon-button/IconButtonBasic.vue
  packages/documentation/demos/icon-button/IconButtonColors.vue
  packages/documentation/demos/icon-button/IconButtonSizes.vue
  packages/documentation/demos/input/InputBasic.vue
  packages/documentation/demos/layouts/LayoutBasic.vue
  packages/documentation/demos/layouts/LayoutWithSidebar.vue
  packages/documentation/demos/list/ListBasic.vue
  packages/documentation/demos/main/MainBasic.vue
  packages/documentation/demos/menu/MenuBasic.vue
  packages/documentation/demos/skeleton/SkeletonBasic.vue
  packages/documentation/demos/stepper/StepperBasic.vue
  packages/documentation/demos/toolbar/ToolbarBasic.vue
  packages/documentation/demos/tree/TreeBasic.vue
  packages/documentation/demos/virtual-scroll/VirtualScrollBasic.vue
  packages/ui/scripts/buildPlugin.ts
  packages/ui/src/components/container/container.css
  packages/ui/src/components/container/container.vue
  packages/ui/src/styles/tokens/acv/custom/breakpoints.css
Labels: size/m

#43 fix(button): fix button types
  packages/documentation/.vitepress/configuration/examples.ts
  packages/documentation/components/button/button.doc.md
  packages/documentation/demos/button/ButtonColorDanger.vue
  packages/documentation/demos/button/ButtonColorInfo.vue
  packages/documentation/demos/button/ButtonColorInverted.vue
  packages/documentation/demos/button/ButtonColorSuccess.vue
  packages/documentation/demos/button/ButtonColorWarning.vue
  packages/documentation/demos/button/ButtonDocSizes.vue
  packages/documentation/demos/button/ButtonDocStates.vue
  packages/documentation/demos/button/ButtonDocTypes.vue
  packages/documentation/demos/button/ButtonDocWithIcons.vue
  packages/documentation/examples/button.md
  packages/documentation/examples/button/colors.md
  packages/documentation/examples/button/pill.md
  packages/documentation/examples/button/sizes.md
  packages/documentation/examples/button/squared.md
  packages/documentation/examples/button/types.md
  packages/documentation/examples/button/variants.md
  packages/ui/src/components/button/button.md
  packages/ui/src/components/button/button.ts
  packages/ui/src/components/button/button.vue
  packages/ui/src/components/confirm-dialog/confirmDialog.spec.ts
  packages/ui/src/components/icon-button/iconButton.spec.ts
Labels: size/l

#44 docs(icons): update icons list
  packages/documentation/demos/icon-internal/IconAcronis.vue
  packages/documentation/theming/icons.md
Labels: size/s

#46 chore(list): fix dead links
  packages/documentation/components/list/list.doc.md
Labels: size/xs

#47 docs(link): update link demos
  packages/documentation/.vitepress/theme/vitepress/index.css
  packages/documentation/components/accordion/accordion.doc.md
  packages/documentation/components/breadcrumbs/breadcrumbs.doc.md
  packages/documentation/components/button/button.doc.md
  packages/documentation/components/carousel/carousel.doc.md
  packages/documentation/components/checkbox/checkbox.doc.md
  packages/documentation/components/combobox/combobox.doc.md
  packages/documentation/components/dialog/dialog.doc.md
  packages/documentation/components/link/link.doc.md
  packages/documentation/components/list/list.doc.md
  packages/documentation/components/radio/radio.doc.md
  packages/documentation/components/table/table.doc.md
  packages/documentation/components/tabs/tabs.doc.md
  packages/documentation/components/tooltip/tooltip.doc.md
  packages/documentation/demos/link/LinkStates.vue
  packages/documentation/examples/link.md
  packages/ui/cypress/snapshots/src/components/link/link.cy.ts/link-basic.snap.png
  packages/ui/cypress/snapshots/src/components/link/link.cy.ts/link-states.snap.png
  packages/ui/src/components/accordion/accordion.md
  packages/ui/src/components/breadcrumbs/breadcrumbs.md
  packages/ui/src/components/button/button.md
  packages/ui/src/components/carousel/carousel.md
  packages/ui/src/components/checkbox/checkbox.md
  packages/ui/src/components/combobox/combobox.md
  packages/ui/src/components/dialog/dialog.md
  packages/ui/src/components/link/link.css
  packages/ui/src/components/link/link.cy.ts
  packages/ui/src/components/link/link.md
  packages/ui/src/components/link/link.vue
  packages/ui/src/components/list/list.md
  packages/ui/src/components/radio/radio.md
  packages/ui/src/components/table/table.md
  packages/ui/src/components/tabs/tabs.md
  packages/ui/src/components/tooltip/tooltip.md
Labels: size/m

#49 fix(charts): add vue chartjs charts
  packages/documentation/.vitepress/configuration/components.ts
  packages/documentation/components/chart/chart.doc.md
  packages/documentation/demos/chart/ChartArea.vue
  packages/documentation/demos/chart/ChartBasic.vue
  packages/documentation/demos/chart/ChartBubble.vue
  packages/documentation/demos/chart/ChartDonut.vue
  packages/documentation/demos/chart/ChartLine.vue
  packages/documentation/demos/chart/ChartMixed.vue
  packages/documentation/demos/chart/ChartPie.vue
  packages/documentation/demos/chart/ChartPolar.vue
  packages/documentation/demos/chart/ChartRadar.vue
  packages/documentation/demos/chart/ChartScatter.vue
  packages/ui/src/components/chart/chart.md
  packages/ui/src/components/chart/chart.spec.ts
  packages/ui/src/components/chart/chart.ts
  packages/ui/src/components/chart/chart.vue
  packages/ui/src/components/chart/public.ts
  packages/ui/src/components/chart/typedCharts.ts
  packages/ui/src/components/chart/utils.ts
  packages/ui/src/components/chip/chip.vue
  packages/ui/src/utils/color-converters.js
  packages/ui/src/utils/color-utils.ts
  packages/ui/src/widgets/pie-chart/chart-legend.scss
  packages/ui/src/widgets/pie-chart/chart-tooltip.scss
  packages/ui/src/widgets/pie-chart/pieChart.vue
Labels: size/xl

#53 feat(carousel): carousel component first iteration
  packages/documentation/demos/carousel/CarouselAutoPlay.vue
  packages/documentation/demos/carousel/CarouselBasic.vue
  packages/documentation/demos/carousel/CarouselHeight.vue
  packages/documentation/demos/carousel/CarouselHover.vue
  packages/documentation/demos/carousel/CarouselIndicators.vue
  packages/documentation/demos/carousel/CarouselNavigation.vue
  packages/documentation/demos/carousel/CarouselSlide.vue
  packages/documentation/demos/carousel/CarouselSlides.vue
  packages/ui/src/components/carousel/carousel.md
  packages/ui/src/components/carousel/carousel.spec.ts
  packages/ui/src/components/carousel/carousel.ts
  packages/ui/src/components/carousel/carousel.vue
  packages/ui/src/components/carousel/carouselItem.vue
Labels: size/m
